/* eslint-disable quote-props */
/* eslint-disable quotes */
exports.exampleCurrentlyPlayingResponse = {
  "timestamp": 1563218531272,
  "context": {
    "external_urls": {
      "spotify": "https://open.spotify.com/playlist/3kGABGhXM4zjtU2fNcgNY7"
    },
    "href": "https://api.spotify.com/v1/playlists/3kGABGhXM4zjtU2fNcgNY7",
    "type": "playlist",
    "uri": "spotify:user:inclushe:playlist:3kGABGhXM4zjtU2fNcgNY7"
  },
  "progress_ms": 243684,
  "item": {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1kR99O4MgSTasyeJh8UFCg"
          },
          "href": "https://api.spotify.com/v1/artists/1kR99O4MgSTasyeJh8UFCg",
          "id": "1kR99O4MgSTasyeJh8UFCg",
          "name": "DJ Koze",
          "type": "artist",
          "uri": "spotify:artist:1kR99O4MgSTasyeJh8UFCg"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/6FnFtxp19taWYbITDtdEfq"
      },
      "href": "https://api.spotify.com/v1/albums/6FnFtxp19taWYbITDtdEfq",
      "id": "6FnFtxp19taWYbITDtdEfq",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/be029d4ccc472fb43851305bd64d8ed45a758ba4",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/a45a8a2de4e90ad478ae7ebe131cc47955b60ba2",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ad98076cb6c508301e1b1126c4049c9a95907283",
          "width": 64
        }
      ],
      "name": "Reincarnations, Pt. 2 - The Remix Chapter 2009 - 2014",
      "release_date": "2014-10-24",
      "release_date_precision": "day",
      "total_tracks": 14,
      "type": "album",
      "uri": "spotify:album:6FnFtxp19taWYbITDtdEfq"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/3NUtpWpGDoffm3RCGhSHtl"
        },
        "href": "https://api.spotify.com/v1/artists/3NUtpWpGDoffm3RCGhSHtl",
        "id": "3NUtpWpGDoffm3RCGhSHtl",
        "name": "Mount Kimbie",
        "type": "artist",
        "uri": "spotify:artist:3NUtpWpGDoffm3RCGhSHtl"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 490663,
    "explicit": false,
    "external_ids": {
      "isrc": "DEMM11400018"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/2eQog4rHlk8OVhJj2uiEHx"
    },
    "href": "https://api.spotify.com/v1/tracks/2eQog4rHlk8OVhJj2uiEHx",
    "id": "2eQog4rHlk8OVhJj2uiEHx",
    "is_local": false,
    "name": "Made to Stray - DJ Koze Remix",
    "popularity": 26,
    "preview_url": "https://p.scdn.co/mp3-preview/77fd52edfab670e3b76ec1e42be47acda96c2ceb?cid=1130bb87f6ea402e98afed27aee886c8",
    "track_number": 6,
    "type": "track",
    "uri": "spotify:track:2eQog4rHlk8OVhJj2uiEHx"
  },
  "currently_playing_type": "track",
  "actions": {
    "disallows": {
      "resuming": true
    }
  },
  "is_playing": true
}
